# Generated by Django 2.2.7 on 2019-11-25 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("puzzles", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=128)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("response", models.TextField(default="")),
                (
                    "_status",
                    models.CharField(
                        choices=[
                            ("NEW", "NEW"),
                            ("SUBMITTED", "SUBMITTED"),
                            ("CORRECT", "CORRECT"),
                            ("INCORRECT", "INCORRECT"),
                        ],
                        default="NEW",
                        max_length=10,
                    ),
                ),
                (
                    "puzzle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guesses",
                        to="puzzles.Puzzle",
                    ),
                ),
            ],
        ),
    ]
