# Generated by Django 2.2.7 on 2019-11-23 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('puzzles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=128)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('_status', models.CharField(choices=[('NEW', 'NEW'), ('SUBMITTED', 'SUBMITTED'), ('CORRECT', 'CORRECT'), ('INCORRECT', 'INCORRECT')], default='NEW', max_length=10)),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guesses', to='puzzles.Puzzle')),
            ],
        ),
    ]
