# Generated by Django 2.2.7 on 2019-11-24 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='response',
            field=models.TextField(default=''),
        ),
    ]
