# Generated by Django 2.2.7 on 2019-11-25 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("answers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="_status",
            field=models.CharField(
                choices=[
                    ("NEW", "NEW"),
                    ("SUBMITTED", "SUBMITTED"),
                    ("CORRECT", "CORRECT"),
                    ("INCORRECT", "INCORRECT"),
                    ("PARTIAL", "PARTIAL"),
                ],
                default="NEW",
                max_length=10,
            ),
        ),
    ]
