# Generated by Django 2.2.8 on 2019-12-05 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0002_auto_20191125_0817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='_status',
            new_name='status',
        ),
    ]
