# Generated by Django 3.1.4 on 2020-12-30 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("answers", "0005_answer_updated_on"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="answer",
            options={"ordering": ("created_on",)},
        ),
    ]
