# Generated by Django 4.0.1 on 2022-01-17 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("answers", "0006_auto_20201229_1902"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="response",
            field=models.TextField(blank=True, default=""),
        ),
    ]
