# Generated by Django 4.1.13 on 2023-12-22 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("answers", "0007_alter_answer_response"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
