# Generated by Django 4.2.17 on 2024-12-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("answers", "0008_alter_answer_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="answer",
            name="restored_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="answer",
            name="transaction_id",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
