# Generated by Django 3.1.4 on 2020-12-04 07:47

from django.db import migrations
from django.template.defaultfilters import slugify


# Saving a Hunt object will generate a name-based slug if it's empty.
def save_existing_hunts(apps, schema_editor):
    Hunt = apps.get_model("hunts", "Hunt")
    for hunt in Hunt.objects.all():
        hunt.save()


class Migration(migrations.Migration):

    dependencies = [
        ("hunts", "0002_hunt_slug"),
    ]

    operations = [
        migrations.RunPython(
            save_existing_hunts,
            reverse_code=migrations.RunPython.noop,
        )
    ]
