# Generated by Django 2.2.13 on 2020-11-28 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hunts", "0003_populate_hunt_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hunt",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
