# Generated by Django 3.1.4 on 2020-12-18 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hunts", "0004_unique_hunt_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="hunt",
            name="answer_queue_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
