# Generated by Django 3.1.4 on 2021-01-06 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hunts", "0005_hunt_answer_queue_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="hunt",
            name="start_time",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="hunt",
            name="end_time",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
