# Generated by Django 3.1.5 on 2021-01-14 06:43

from django.db import migrations, models
import hunts.models


class Migration(migrations.Migration):

    dependencies = [
        ("hunts", "0006_start_end_times"),
    ]

    operations = [
        migrations.AddField(
            model_name="hunt",
            name="feeder_sound",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=16,
                null=True,
                validators=[hunts.models.Hunt.validate_file_exists],
            ),
        ),
        migrations.AddField(
            model_name="hunt",
            name="meta_sound",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=16,
                null=True,
                validators=[hunts.models.Hunt.validate_file_exists],
            ),
        ),
    ]
