# Generated by Django 3.1.4 on 2021-01-13 03:33

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("hunts", "0006_start_end_times"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoogleInfo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hunt_folder_id", models.CharField(max_length=44)),
                (
                    "autogenerated_sheets_folder_id",
                    models.CharField(blank=True, editable=False, max_length=44),
                ),
                (
                    "human_files_folder_id",
                    models.CharField(blank=True, editable=False, max_length=44),
                ),
                (
                    "sheets_template_file_id",
                    models.CharField(blank=True, editable=False, max_length=44),
                ),
                (
                    "whitelisted_emails",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.EmailField(max_length=254),
                        blank=True,
                        size=None,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="hunt",
            name="group",
            field=models.OneToOneField(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="auth.group",
            ),
        ),
        migrations.AddField(
            model_name="hunt",
            name="google_ids",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="hunts.googleinfo",
            ),
        ),
    ]
