# Generated by Django 3.1.5 on 2021-01-15 02:37

from django.db import migrations, models
import hunts.models


class Migration(migrations.Migration):

    dependencies = [
        ("hunts", "0007_auto_20210114_0143"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hunt",
            name="feeder_sound",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=64,
                null=True,
                validators=[hunts.models.Hunt.validate_file_exists],
            ),
        ),
        migrations.AlterField(
            model_name="hunt",
            name="meta_sound",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=64,
                null=True,
                validators=[hunts.models.Hunt.validate_file_exists],
            ),
        ),
    ]
