# Generated by Django 4.0.1 on 2022-01-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hunts", "0009_remove_huntsettings_discord_text_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="huntsettings",
            name="google_sheets_template_folder_id",
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
