# Generated by Django 4.1.4 on 2022-12-27 20:57

from django.db import migrations, models


def copy_answer_queue_enabled(apps, schema_editor):
    Hunt = apps.get_model("hunts", "Hunt")
    for hunt in Hunt.objects.all():
        hunt.settings.answer_queue_enabled = hunt.answer_queue_enabled
        hunt.settings.save()


class Migration(migrations.Migration):

    dependencies = [
        ("hunts", "0010_huntsettings_google_sheets_template_folder_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="huntsettings",
            name="answer_queue_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(copy_answer_queue_enabled),
    ]
