# Generated by Django 4.1.4 on 2022-12-27 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hunts", "0011_huntsettings_answer_queue_enabled"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hunt",
            name="answer_queue_enabled",
        ),
    ]
