# Generated by Django 4.1.4 on 2023-01-02 19:58

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hunts", "0012_remove_hunt_answer_queue_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="huntsettings",
            name="active_user_lookback",
            field=models.DurationField(
                default=datetime.timedelta(seconds=600),
                help_text="Amount of time to look back for active users of a puzzle.",
            ),
        ),
    ]
