# Generated by Django 4.1.13 on 2023-12-22 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hunts", "0014_hunt_last_active_users_update_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hunt",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="huntsettings",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
