# Generated by Django 3.1.4 on 2020-12-21 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatRoom",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service",
                    models.CharField(choices=[("DISCORD", "DISCORD")], max_length=32),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "text_channel_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "voice_channel_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="chatroom",
            constraint=models.UniqueConstraint(
                fields=("service", "name"), name="unique_room_name_per_service"
            ),
        ),
    ]
