# Generated by Django 3.1.4 on 2020-12-23 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chatroom",
            old_name="voice_channel_id",
            new_name="audio_channel_id",
        ),
    ]
