# Generated by Django 3.1.4 on 2021-01-01 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_auto_20201230_1705"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chatroom",
            old_name="audio_invite_url",
            new_name="audio_channel_url",
        ),
        migrations.RenameField(
            model_name="chatroom",
            old_name="text_invite_url",
            new_name="text_channel_url",
        ),
    ]
