# Generated by Django 3.1.4 on 2021-01-12 09:26

import chat.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0006_start_end_times'),
        ('chat', '0006_auto_20210101_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('DISCORD', 'DISCORD')], default=chat.models._get_default_service, max_length=32)),
                ('name', models.CharField(max_length=100)),
                ('role_id', models.CharField(max_length=255)),
                ('hunt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_roles', to='hunts.hunt')),
            ],
        ),
    ]
