# Generated by Django 4.1.4 on 2022-12-26 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_chatrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='audio_channel_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='text_channel_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
