# Generated by Django 4.1.13 on 2024-12-15 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0009_alter_chatrole_id_alter_chatroom_id"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="chatroom",
            name="unique_room_name_per_service",
        ),
    ]
