# Generated by Django 4.2.17 on 2024-12-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0010_remove_chatroom_unique_room_name_per_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="restored_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="transaction_id",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
