# Generated by Django 2.2.13 on 2020-11-28 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzler',
            name='last_accessed_hunt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hunts.Hunt'),
        ),
    ]
