# Generated by Django 3.1.4 on 2020-12-17 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_puzzler_last_accessed_hunt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="puzzler",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
    ]
