# Generated by Django 4.1.13 on 2023-12-22 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_auto_20201217_0019"),
    ]

    operations = [
        migrations.AlterField(
            model_name="puzzler",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
