# Generated by Django 4.1.13 on 2024-01-09 22:29

import django.db.migrations.operations.special
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("puzzles", "0001_initial"),
        ("puzzles", "0002_auto_20191128_0657"),
        ("puzzles", "0003_auto_20191201_2037"),
        ("puzzles", "0004_auto_20191201_1757"),
        ("puzzles", "0005_puzzle_tags"),
        ("puzzles", "0006_auto_20191207_2133"),
        ("puzzles", "0007_auto_20191207_2222"),
        ("puzzles", "0008_auto_20191208_0317"),
        ("puzzles", "0009_auto_20191214_0257"),
        ("puzzles", "0010_puzzletag_is_meta"),
        ("puzzles", "0011_auto_20191215_1018"),
        ("puzzles", "0012_puzzle_active_users"),
        ("puzzles", "0013_auto_20191220_0243"),
        ("puzzles", "0014_remove_puzzle_channel"),
        ("puzzles", "0015_auto_20201130_0715"),
        ("puzzles", "0016_auto_20201217_0019"),
        ("puzzles", "0017_auto_20201217_0626"),
        ("puzzles", "0018_auto_20201217_0707"),
        ("puzzles", "0019_auto_20201217_0708"),
        ("puzzles", "0020_auto_20201217_0824"),
    ]

    initial = True

    dependencies = [
        ("answers", "0003_auto_20191204_2308"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hunts", "0004_unique_hunt_slug"),
        ("hunts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PuzzleTag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Name"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="Slug"),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("primary", "blue"),
                            ("secondary", "gray"),
                            ("success", "green"),
                            ("danger", "red"),
                            ("warning", "yellow"),
                            ("light", "white"),
                            ("dark", "black"),
                        ],
                        default="primary",
                        max_length=10,
                    ),
                ),
                ("is_meta", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PuzzleTagThrough",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "object_id",
                    models.IntegerField(db_index=True, verbose_name="Object id"),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="puzzles_puzzletagthrough_tagged_items",
                        to="contenttypes.contenttype",
                        verbose_name="Content type",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tagged_items",
                        to="puzzles.puzzletag",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Puzzle",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("url", models.URLField(blank=True)),
                (
                    "sheet",
                    models.URLField(blank=True, default=None, null=True, unique=True),
                ),
                ("notes", models.TextField(default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SOLVING", "SOLVING"),
                            ("PENDING", "PENDING"),
                            ("SOLVED", "SOLVED"),
                            ("STUCK", "STUCK"),
                            ("EXTRACTION", "EXTRACTION"),
                        ],
                        default="SOLVING",
                        max_length=10,
                    ),
                ),
                ("answer", models.CharField(max_length=128)),
                (
                    "hunt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="puzzles",
                        to="hunts.hunt",
                    ),
                ),
                ("is_meta", models.BooleanField(default=False)),
                (
                    "metas",
                    models.ManyToManyField(related_name="feeders", to="puzzles.puzzle"),
                ),
                (
                    "active_users",
                    models.ManyToManyField(
                        related_name="active_puzzles", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="puzzle",
            constraint=models.UniqueConstraint(
                fields=("name", "hunt"), name="unique_names_per_hunt"
            ),
        ),
        migrations.AlterField(
            model_name="puzzletag",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="puzzletag",
            name="slug",
            field=models.SlugField(max_length=100, unique=True, verbose_name="slug"),
        ),
        migrations.AlterField(
            model_name="puzzletagthrough",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="puzzles_puzzletagthrough_tagged_items",
                to="contenttypes.contenttype",
                verbose_name="content type",
            ),
        ),
        migrations.AlterField(
            model_name="puzzletagthrough",
            name="object_id",
            field=models.IntegerField(db_index=True, verbose_name="object ID"),
        ),
        migrations.RunSQL(
            sql="CREATE TABLE tagthrough_temp AS SELECT object_id, tag_id FROM puzzles_puzzletagthrough;",
        ),
        migrations.RemoveField(
            model_name="puzzletag",
            name="slug",
        ),
        migrations.AddField(
            model_name="puzzletag",
            name="hunt",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="puzzle_tags",
                to="hunts.hunt",
            ),
        ),
        migrations.AddField(
            model_name="puzzle",
            name="tags",
            field=models.ManyToManyField(
                related_name="puzzles", to="puzzles.puzzletag"
            ),
        ),
        migrations.RunSQL(
            sql=[
                "INSERT INTO puzzles_puzzle_tags (puzzle_id, puzzletag_id) SELECT object_id, tag_id FROM tagthrough_temp;",
                "DROP TABLE tagthrough_temp;",
            ],
        ),
        migrations.AlterField(
            model_name="puzzletag",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name="PuzzleTagThrough",
        ),
        migrations.AlterField(
            model_name="puzzletag",
            name="hunt",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="puzzle_tags",
                to="hunts.hunt",
            ),
        ),
        migrations.AddConstraint(
            model_name="puzzletag",
            constraint=models.UniqueConstraint(
                fields=("name", "hunt"), name="unique_tag_names_per_hunt"
            ),
        ),
    ]
