# Generated by Django 2.2.7 on 2019-11-18 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('url', models.URLField()),
                ('sheet', models.URLField()),
                ('channel', models.URLField()),
                ('notes', models.TextField()),
                ('status', models.CharField(choices=[('NEW', 'NEW'), ('SOLVED', 'SOLVED'), ('STUCK', 'STUCK')], default='NEW', max_length=10)),
            ],
        ),
    ]
