# Generated by Django 2.2.7 on 2019-11-18 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='puzzle',
            old_name='title',
            new_name='name',
        ),
    ]
