# Generated by Django 2.2.7 on 2019-11-24 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='answer',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='status',
            field=models.CharField(choices=[('SOLVING', 'SOLVING'), ('PENDING', 'PENDING'), ('SOLVED', 'SOLVED'), ('STUCK', 'STUCK')], default='SOLVING', max_length=10),
        ),
    ]
