# Generated by Django 2.2.7 on 2019-11-25 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0002_auto_20191124_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metapuzzle',
            name='feeder',
        ),
        migrations.AddField(
            model_name='metapuzzle',
            name='feeders',
            field=models.ManyToManyField(related_name='metas', to='puzzles.Puzzle'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
