# Generated by Django 2.2.7 on 2019-12-08 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0005_puzzle_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='status',
            field=models.CharField(choices=[('SOLVING', 'SOLVING'), ('PENDING', 'PENDING'), ('SOLVED', 'SOLVED'), ('STUCK', 'STUCK'), ('EXTRACTION', 'EXTRACTION')], default='SOLVING', max_length=10),
        ),
    ]
