# Generated by Django 2.2.7 on 2019-12-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0007_auto_20191207_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='metas',
            field=models.ManyToManyField(to='puzzles.Puzzle'),
        ),
    ]
