# Generated by Django 2.2.8 on 2019-12-15 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("puzzles", "0009_auto_20191214_0257"),
    ]

    operations = [
        migrations.AddField(
            model_name="puzzletag",
            name="is_meta",
            field=models.BooleanField(default=False),
        ),
    ]
