# Generated by Django 2.2.7 on 2019-12-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0010_puzzletag_is_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='metas',
            field=models.ManyToManyField(related_name='feeders', to='puzzles.Puzzle'),
        ),
    ]
