# Generated by Django 2.2.7 on 2019-12-15 18:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("puzzles", "0011_auto_20191215_1018"),
    ]

    operations = [
        migrations.AddField(
            model_name="puzzle",
            name="active_users",
            field=models.ManyToManyField(
                related_name="active_puzzles", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
