# Generated by Django 2.2.7 on 2019-12-20 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("puzzles", "0012_puzzle_active_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="puzzle",
            name="url",
            field=models.URLField(blank=True),
        ),
    ]
