# Generated by Django 2.2.13 on 2020-11-24 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('puzzles', '0014_auto_20201124_0031'), ('puzzles', '0015_auto_20201124_0035'), ('puzzles', '0016_auto_20201124_0041'), ('puzzles', '0017_auto_20201124_0103')]

    dependencies = [
        ('puzzles', '0013_auto_20191220_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.AddConstraint(
            model_name='puzzle',
            constraint=models.UniqueConstraint(fields=('name', 'hunt'), name='unique_names'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='channel',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddConstraint(
            model_name='puzzle',
            constraint=models.UniqueConstraint(fields=('channel', 'hunt'), name='unique_channels'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='channel',
            field=models.CharField(default='', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='sheet',
            field=models.URLField(default='', null=True, unique=True),
        ),
        migrations.RemoveConstraint(
            model_name='puzzle',
            name='unique_channels',
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='channel',
            field=models.CharField(default='', max_length=128, null=True, unique=True),
        ),
    ]
