# Generated by Django 2.2.13 on 2020-11-27 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("puzzles", "0013_auto_20191220_0243"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="puzzle",
            name="channel",
        ),
    ]
