# Generated by Django 3.1.4 on 2020-12-17 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hunts", "0004_unique_hunt_slug"),
        ("puzzles", "0016_auto_20201217_0019"),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE TABLE tagthrough_temp AS "
            "SELECT object_id, tag_id FROM puzzles_puzzletagthrough;"
        ),
        migrations.RemoveField(
            model_name="puzzletag",
            name="slug",
        ),
        migrations.AddField(
            model_name="puzzletag",
            name="hunt",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="puzzle_tags",
                to="hunts.hunt",
            ),
        ),
        migrations.RemoveField(
            model_name="puzzle",
            name="tags",
        ),
        migrations.AddField(
            model_name="puzzle",
            name="tags",
            field=models.ManyToManyField(
                related_name="puzzles", to="puzzles.PuzzleTag"
            ),
        ),
        migrations.RunSQL(
            [
                "INSERT INTO puzzles_puzzle_tags (puzzle_id, puzzletag_id) "
                "SELECT object_id, tag_id "
                "FROM tagthrough_temp;",
                "DROP TABLE tagthrough_temp;",
            ]
        ),
        migrations.AlterField(
            model_name="puzzletag",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name="PuzzleTagThrough",
        ),
    ]
