# Generated by Django 3.1.4 on 2020-12-17 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("puzzles", "0018_auto_20201217_0707"),
    ]

    operations = [
        migrations.AlterField(
            model_name="puzzletag",
            name="hunt",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="puzzle_tags",
                to="hunts.hunt",
            ),
        ),
    ]
