# Generated by Django 3.1.4 on 2020-12-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("puzzles", "0019_auto_20201217_0708"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="puzzletag",
            constraint=models.UniqueConstraint(
                fields=("name", "hunt"), name="unique_tag_names_per_hunt"
            ),
        ),
    ]
