# Generated by Django 3.1.4 on 2020-12-18 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("puzzles", "0020_auto_20201217_0824"),
    ]

    operations = [
        migrations.AddField(
            model_name="puzzle",
            name="discord_channel_id",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
