# Generated by Django 3.1.4 on 2020-12-21 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
        ("puzzles", "0021_puzzle_discord_channel_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="puzzle",
            name="chat_room",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="chat.chatroom",
                unique=True,
            ),
        ),
    ]
