# Generated by Django 3.1.4 on 2020-12-21 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
        ("puzzles", "0022_puzzle_chat_room"),
    ]

    operations = [
        migrations.AlterField(
            model_name="puzzle",
            name="chat_room",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="chat.chatroom",
            ),
        ),
    ]
