# Generated by Django 3.1.4 on 2021-01-04 20:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("puzzles", "0023_auto_20201221_0030"),
    ]

    operations = [
        migrations.AddField(
            model_name="puzzle",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="puzzle",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
