# Generated by Django 4.0 on 2022-01-03 04:34
from django.contrib.postgres.operations import CITextExtension
import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("puzzles", "0025_auto_20210109_0728"),
    ]

    operations = [
        CITextExtension(),
        migrations.AlterField(
            model_name="puzzletag",
            name="name",
            field=django.contrib.postgres.fields.citext.CICharField(max_length=100),
        ),
    ]
