# Generated by Django 4.0.1 on 2022-01-17 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0007_chatrole"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("puzzles", "0027_alter_puzzletag_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="puzzle",
            name="active_users",
            field=models.ManyToManyField(
                blank=True, related_name="active_puzzles", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="puzzle",
            name="answer",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name="puzzle",
            name="chat_room",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="chat.chatroom",
            ),
        ),
        migrations.AlterField(
            model_name="puzzle",
            name="metas",
            field=models.ManyToManyField(
                blank=True, related_name="feeders", to="puzzles.Puzzle"
            ),
        ),
        migrations.AlterField(
            model_name="puzzle",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="puzzle",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="puzzles", to="puzzles.PuzzleTag"
            ),
        ),
        migrations.AlterField(
            model_name="puzzle",
            name="url",
            field=models.URLField(),
        ),
    ]
