# Generated by Django 4.1.4 on 2022-12-28 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("puzzles", "0029_alter_puzzletag_options_puzzletag_is_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="puzzletag",
            name="is_location",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="puzzletag",
            name="color",
            field=models.CharField(
                choices=[
                    ("primary", "blue"),
                    ("secondary", "gray"),
                    ("success", "green"),
                    ("danger", "red"),
                    ("warning", "yellow"),
                    ("light", "white"),
                    ("dark", "black"),
                    ("info", "teal"),
                ],
                default="primary",
                max_length=10,
            ),
        ),
    ]
