# Generated by Django 4.1.4 on 2022-12-31 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("puzzles", "0030_puzzletag_is_location_alter_puzzletag_color"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="puzzletag",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("is_location", False),
                        models.Q(("color", "info"), _negated=True),
                    ),
                    models.Q(("is_location", True), ("color", "info")),
                    _connector="OR",
                ),
                name="puzzles_puzzletag_location_color",
            ),
        ),
        migrations.AddConstraint(
            model_name="puzzletag",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("is_meta", False), models.Q(("color", "dark"), _negated=True)
                    ),
                    models.Q(("is_meta", True), ("color", "dark")),
                    _connector="OR",
                ),
                name="puzzles_puzzletag_meta_color",
            ),
        ),
    ]
