# Generated by Django 4.1.4 on 2023-01-01 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("puzzles", "0031_puzzletag_puzzles_puzzletag_location_color_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="puzzle",
            name="active_users",
        ),
    ]
