# Generated by Django 4.1.4 on 2023-01-02 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("puzzles", "0032_remove_puzzle_active_users"),
    ]

    operations = [
        migrations.CreateModel(
            name="PuzzleActivity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_edit_time", models.DateTimeField()),
                (
                    "puzzle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="puzzles.puzzle"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "puzzle activities",
                "default_related_name": "puzzle_activities",
            },
        ),
        migrations.AddField(
            model_name="puzzle",
            name="active_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="active_puzzles",
                through="puzzles.PuzzleActivity",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="puzzleactivity",
            constraint=models.UniqueConstraint(
                fields=("user", "puzzle"), name="unique_user_puzzle_activity_entry"
            ),
        ),
    ]
