# Generated by Django 4.2.17 on 2025-01-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("puzzles", "0035_puzzles_soft_delete"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="puzzle",
            name="unique_names_per_hunt",
        ),
        migrations.AddConstraint(
            model_name="puzzle",
            constraint=models.UniqueConstraint(
                fields=("name", "hunt", "deleted_at"), name="unique_names_per_hunt"
            ),
        ),
    ]
