name: pre-commit

on:
  pull_request:
  push:
    branches: [master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.0
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - name: Install python deps
        run: pip install -r requirements.txt

      - name: Configure test environment
        run: cp .env.test .env

      - name: Run all tests with coverage
        run: |
          python manage.py migrate  # Tests require initial database migration.
          python manage.py collectstatic  # Tests require static files.
          coverage run --source='.' manage.py test

      - name: Upload coverage data
        uses: codecov/codecov-action@v1
